name: ci

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.1.0

      - uses: actions/cache@v4.0.2
        id: pnpm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - run: pnpm run build
      - run: pnpm run test

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true
