name: publish-sandbox

on:
  push:
    branches:
      - main

jobs:
  publish-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.1.0

      - run: cd demo

      - uses: actions/cache@v4.0.2
        id: pnpm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
